### ISSUE TITLE
BIRT 4.14.0 OSGI version seems to be broken

### ISSUE THREAD

**Issue by speckyspooky** [eclipse-birt/birt#1340]
Based on the discussion #1331 I tested the latest BIRT 4.14.0 builts designer and the OSGI-version.

And it seems to me that the latest built are brooken because the birt-service couldn't be loaded on Tomcat.

Testing - Windows System:

- Tomcat 9.0.52, Java 17.0.5+8 Eclipse Adoptium
- Tomcat 9.0.76, Java 17.0.5+8 Eclipse Adoptium

Both installation was tested with the following birt versions:
- birt-runtime-osgi-4.13.0-20230302: service could be started and viewer example is available
- birt-runtime-osgi-4.14.0-20230604: service could be started and viewer example is available
- birt-runtime-osgi-4.14.0-20230610: service start crashed
- birt-runtime-osgi-4.14.0-20230612: service start crashed

Attached the both Tomcat error logs of 9.0.52 (same error on 9.0.76)
[tomcat-9.0.52-stderr.birt-osgi-4.14.0-20230610.zip](https://github.com/eclipse-birt/birt/files/11839931/tomcat-9.0.52-stderr.birt-osgi-4.14.0-20230610.zip)
[tomcat-9.0.52-stderr.birt-osgi-4.14.0-20230612.zip](https://github.com/eclipse-birt/birt/files/11839932/tomcat-9.0.52-stderr.birt-osgi-4.14.0-20230612.zip)

What I not understand on the eror log is the origin, is it an Tomcat issue or may be a missing dependency topic of BIRT 4.14.0 (because 4.13.0 is running)
Main error:
	Caused by: java.lang.NoClassDefFoundError: javax/xml/soap/SOAPException
	Caused by: java.lang.ClassNotFoundException: javax.xml.soap.SOAPException

![no-class-def-found-error](https://github.com/eclipse-birt/birt/assets/41593722/678933a4-369e-4fbf-9060-e08ff5447ba0)

On my research I found the following article which is very old and at the end, have we here a task for the new built process to add missing dependencies or is it realy a Tomcat configuration issue.

https://stackoverflow.com/questions/48626824/java-lang-noclassdeffounderror-javax-xml-soap-soapexception

**Comment by speckyspooky** [comment]
@merks 
As an specialist of the built process & dependencies, could you please take a look here.
Perhaps you have an idea to solve the issue with the built process optimization (#1286) when it is a dependency topic.

**Comment by merks** [comment]
The feature includes the javax.xml.soap bundle

![image](https://github.com/eclipse-birt/birt/assets/208716/07bf4bda-0a5d-437f-b9b1-809c44672525)

These things export that exception class:

![image](https://github.com/eclipse-birt/birt/assets/208716/f559d532-3791-46c1-8c76-163f1270c171)

In the runtime test (recall where testing OSGi doesn't work at all), I don't see that jar mentioned:

![image](https://github.com/eclipse-birt/birt/assets/208716/d6909a76-a23f-4dcc-8497-a9bc7e034106)

That's like what I see too for this download:

https://download.eclipse.org/birt/updates/nightly/N202306121255/downloads/birt-runtime-osgi-4.14.0-202306121255.zip

There seem to be a many poorly-maintained and ill-defined ant scripts involved in building things.  😱 

Can someone explain the the split between plugins and libs in OSGi runtime?

How does one discover that the OSGi runtime is incomplete?   There should be a test that launches the use of this thing the same way as it's used in the picture above...

**Comment by merks** [comment]
It seems missing from the 4.13 release versions as well.  Was that broken too?

Oddly as well, if I understand correctly, the "birt-runtime-osgi"  not related to the org.eclipse.birt.osgi.runtime feature at all.  It's contents are define partly by what's in this product:

![image](https://github.com/eclipse-birt/birt/assets/208716/a8406e2a-261f-4295-95f0-49f8f6a3c062)

Which includes only what's transitively required by the 'org.eclipse.birt.engine.runtime' feature...

**Comment by merks** [comment]
The build is copying these from the product:

![image](https://github.com/eclipse-birt/birt/assets/208716/c378cc58-fada-4942-afea-ea6894fd5928)

But of course there are things missing.  I think this has not been maintained for a long time; several of the things it's trying to copy are not present.

Also, the tests that test the OSGi runtime current fail for cases of nested jars and that what this build.xml stuff is doing.

So my guess is that any jar in the plugins folder or lib folder that relies on nested jars will fail and that there are arbitrary "missing" things because the product used to build the  OSGi runtime is not using the osgi runtime feature.

Can anyone say when is the last time that this actually worked?  The 4.13 zip doesn't look better.

This feels like a bit of a head bang exercise given I can't easily determine if what's produced is correct.

I do have soap included now:

![image](https://github.com/eclipse-birt/birt/assets/208716/8b7d3982-c2c5-4f54-b8f2-3630a8e3e154)

But when I look in the axis jar (which the build.xml is assuming is a folder not a jar and that it can copy nested jars out of a folder), I see it has these nested jars:

![image](https://github.com/eclipse-birt/birt/assets/208716/829e620b-a28b-4eb5-a255-d76e89437d16)

And there are 255 jars that I'd need to look at to see which other ones are probably wrong.  Ouch.

**Comment by wimjongman** [comment]
Hi Ed, Yes, there are a bunch of cryptic (pre-tycho) Ant scripts created by somebody long ago that are not documented. If we want to supply a BIRT OSGi runtime it should happen using a normal tycho build. There is also a non-osgi runtime. 


What the runtimes do is to headlessly run a BIRT report. Speculating, I can say that people can add drivers, etc.. to the runtime by either supplying them as bundles (osgi runtime) or by adding them into a libs folder for the non-osgi runtime.

**Comment by speckyspooky** [comment]
@merks
Thanks for your investigation on it.
To clarify, yes the BIRT OSGI-version is in used through the community latest responses to your call of usage.
And till version 4.13.0 it runs on my Tomcat.
So the latest official release of March 2023 works well.

Before the built change was started according my notes of my issue the version
birt-runtime-osgi-4.14.0-20230604 was running as well, but with the issue what on the HTML-viewer-page (what is fixed).

Therefore all in all, yes OSGI was working and yes, it is in use through the community.

**Comment by hvbtup** [comment]
Disclaimer: I could be totally wrong, and I never used the OSGI runtime, and I'm an OSGI noob.

IIRC basically the files contained in the OSGI runtime were the same as in the POJO runtime, only with a different file-system layout, and apart from that the only difference is the presence of an env variable BIRT_HOME, which decides during the startup which startup routine is actually called.

I think both of the "runtimes" serve 3 different purposes:
1) Running a single report from the command line (e.g. from any Non-Java program)
2) Embed the runtime into an existing Java application, allowing to run multiple reports in parallel from that application (we could call the application a "BIRT server" then)
3) Using BIRT from a Java web server (accessing reports per http), e.g. in comparison to 2), the "server functionality" is built in.

Personally I only use 2), and the main difference is - as far as I understand it - that the POJO runtime supports 2) and 3) for good old Java application relying on the class path specified as an environment variable or command-line option, whereas the OSGI runtime supports the same for OSGI applications.

BTW, Non-Java applications don't care about OSGI anyway, so we could for remove 1) from the OSGI runtime (that is, remove the shell script), and document that for running reports from the command line, the POJO runtime can be used.

**Comment by merks** [comment]
The test for the OSGi runtime launches like a POJO runtime and that totally does not work; it didn't even add the stuff in the plugins folder.   The test for the POJO runtime actually runs but the test is combined into a single project that tests both runtimes as if they are kind of identical.   I don't get the logic behind that, but the tests stopped being run long ago...


In any case, the current build, when it completes in about 1 hours, will produce an OSGi runtime that includes javax.xml.soap:

https://ci.eclipse.org/birt/job/build/job/master/

**Comment by speckyspooky** [comment]
I will check the version after the built and let you know.

**Comment by merks** [comment]
The latest version has java.xml.soap:

![image](https://github.com/eclipse-birt/birt/assets/208716/2f2c7070-7d4f-4f6f-a8a3-39ef0f297634)

**Comment by speckyspooky** [comment]
I started the retest and I checked the plugin-folde and alos the configuration of "org.eclipse.equinox.simpleconfigurator" for bundle.info.
The organisational result is: yes, the plugin is added as folder and the bundle.info is correct:

![error-4 14 0-1](https://github.com/eclipse-birt/birt/assets/41593722/4277064d-d395-43c3-8ed5-d3a1be6b5037)


The execution of the birt-service-app on Tomcat (9.0.76) failed again, the std-error-msg is the same like before:

![error-4 14 0-2](https://github.com/eclipse-birt/birt/assets/41593722/aa8dea19-7f98-42a4-9f68-1aa29ace26b4)


For my testing I copy the "WebViewerExample"-folder and rename it to "birt".
The error appears directly on the starting moment because the Tomcat cannot deploy the birt-service.

This is the default behavior like my installations before and also the approach of te eclipse-birt-installation description
and in the past it was running.

**Comment by speckyspooky** [comment]
There is one thing which confuse me in full. WHen I copy the whole birt folder (he whole content of the zip-folder)
then the service could be started - BUT the "frameset"-call to execute the reports is not reachable:

Folder structure: 
![run-all](https://github.com/eclipse-birt/birt/assets/41593722/2eb216f7-ce4f-4963-8f27-3e2b5830c7a9)

Acces log, request documentation:
![run-all-viewer](https://github.com/eclipse-birt/birt/assets/41593722/7462d8fc-592a-4c9b-9c60-4c60b1c0fce1)

**Comment by speckyspooky** [comment]
If I use the birt.war on Tomcat for auto-delpoyment then I get the same error on birt-service-start like the manual copy steps of WebViewerExample.

**Comment by merks** [comment]
Unfortunately I have absolutely no understanding of how this runtime is being launched.  The infrastructure to build and assemble it is understood by no one.  I cannot test it myself. There exists no test I can run to test what’s built. It’s like we are using a black box to build a black box. 

How can we move forward from such an impasse?    My capacity to poke at this is limited.  There must be a more well defined pass criterion.

**Comment by merks** [comment]
BTW, mention the WebViewerExample.  It's contents are populated by this part of the Ant script:

https://github.com/eclipse-birt/birt/blob/92c78b3eb97f956808fe42a2c9f22a3016226c10/build/birt-packages/birt-runtime-osgi/build.xml#L69-L81

Apparently parts of that are also copied into the war:

https://github.com/eclipse-birt/birt/blob/92c78b3eb97f956808fe42a2c9f22a3016226c10/build/birt-packages/birt-runtime-osgi/build.xml#L97-L107

These scripts are extreme fragile and make assumptions about what is packaged as a jar versus what is packaged as a directory.

So, for example, for soap is there as a folder but not with nested jars.  So compare the folders here with the assumed libraries being copied:

![image](https://github.com/eclipse-birt/birt/assets/208716/eea680df-2bca-4048-9c40-457219e2b2de)

Someone needs to determine what's missing but definitely the soap directory is not being copied.  But then I don't see that in the old runtimes either.

**Comment by speckyspooky** [comment]
Yes, the soap-library wasn't a folder or single jar on 4.13.0
Therefore I didn't understand the error in full why appears the error not earlier.

Have you an option to test the OSGI on a Tomcat on your side.
Because I can only do run tests and so but I haven't your built ideas. So it is hard to find a solution.

By the way, why is the service running with the whole Zip-folder content but not based on the WebViewerExample (ok, service will run, but not the viewer).

**Comment by merks** [comment]
> Yes, the soap-library wasn't a folder or single jar on 4.13.0 Therefore I didn't understand the error in full why appears the error not earlier.
> 

It may well be that newer dependencies depend on additional things or that different dependency versions break assumptions in Ant scripts that quietly don't complain.

> Have you an option to test the OSGI on a Tomcat on your side. Because I can only do run tests and so but I haven't your built ideas. So it is hard to find a solution.
> 

I don't know how to do that.  I'm not sure how many hours I have to spend to learn how to set up manual testing infrastructure.  Keep in mind that this is not my job and that my volunteer time (and patience) is bounded.

> By the way, why is the service running with the whole Zip-folder content but not based on the WebViewerExample (ok, service will run, but not the viewer).

Firstly, I don't know what this means.  Secondly, this is something that someone with knowledge of the semantics of these things must answer, not someone running builds.  Of course my naive guess would be that something in the whole Zip-folder is missing from the WebViewerExample folder, but that seems evident.  I've already asked things like what does the lib folder mean versus the plugins folder because I see build scripts copying stuff from the latter to the former; build scripts that look broken though maybe have been broken for a long time.

**Comment by speckyspooky** [comment]
I mean with zip-folder-content according to my images from yesterday evening that I unzip the osgi-runtime folder and copied all files to Tomcat into the BIRT-folder. That's all.

**Comment by merks** [comment]
At the root of the zip is a *.war that "duplicates" much of the structure and content of the WebViewerExample and it is apparently more complete or more correct.   Why does this work?  I cannot answer that because I have no knowledge of how this works.  If someone tells me Xyz is missing or incorrect , I can figure out why it's missing or how to correct it, but that is the extent to which I can solve the problem.

**Comment by speckyspooky** [comment]
Later of this weekend I will take a look if I can see a difference of the WebViewerExample and the runtime-folder.
Perhaps I can see some differences.

**Comment by merks** [comment]
Hopefully you can try some copy and paste things.  E.g., maybe the javax.xml.soap* in the plugins folder should be copied to the lib folder.  Note that traveling Monday-Thursday and will not be helpful during that time.

**Comment by merks** [comment]
I suppose it must be a jar and can't be just a folder, right?

 I ask because this dependency seems quite adamant about unpacking itself:

![image](https://github.com/eclipse-birt/birt/assets/208716/b1c4d404-cb3f-4d0e-9d79-536770f4788b)

Even when I modified all the features that include it to tell it not to do that, e.g., 

![image](https://github.com/eclipse-birt/birt/assets/208716/6ef9faca-7d78-4ca4-a08d-8e4db5adf8ce)

Otherwise, I'll need to investigate why always get unjarred in the product install from with the runtimes are built or I must jar it up in the ant step.  (And these builds take **really long** locally too so it's a very long cycle time to tweak these things.)

**Comment by speckyspooky** [comment]
All additional files on the lib-folder are jar-files therefore I think we should there only add directly the soap-jar-file and not the folder.

**Comment by speckyspooky** [comment]
The request includes the fixes for:

- #1346  Renew web viewer parameter dialog & optional flag of textboxes
- #1343  Fix of BIRT WebViewer browser hints
- #1329 improved images of index.jsp

**Comment by merks** [comment]
I hate to make the Ant tasks more ugly, but they really are atrocious already.    I can see that the jar is available in the target/repository/plugins folder so I will copy it from there:

![image](https://github.com/eclipse-birt/birt/assets/208716/d870b31e-6046-420a-9824-e860bd92a51e)

Then I'm going to stop using these entire:

```
property name="DESIGNER_DIR" location="${ROOT_DIR}/build/org.eclipse.birt.p2updatesite/target/products/org.eclipse.birt.designer/win32/win32/x86_64/designer"/>
```

Copying stuff from other projects seems especially horribly error prone, so better to get rid of that!

I'll test locally that this works before creating a PR...

**Comment by speckyspooky** [comment]
The test of osgi-runtime with PR #1349 was successful.

**Comment by merks** [comment]
@speckyspooky 

It seems the command line invocations of the OSGi runtime fails the same way as the "fixed" runtime test of it fails:

> 
> merks@CORE MINGW64 /d/Users/merks/birt-master/git/birt/build/birt-packages/birt-runtime-test/target/birt-runtime-osgi/ReportEngine
> $./genReport.bat samples/hello_world.rptdesign
> OSGI-Mode, BIRT_HOME=D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-test\target\birt-runtime-osgi\ReportEngine\platform
> Java command=java -cp "D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-test\target\birt-runtime-osgi\ReportEngine\lib\*" -DBIRT_HOME=D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-test\target\birt-runtime-osgi\ReportEngine\platform org.eclipse.birt.report.engine.api.ReportRunner samples/hello_world.rptdesign
> Loading Platform
> Loading Platform
> platform=null
> Juni 26, 2023 7:58:11 AM org.eclipse.birt.report.engine.api.ReportRunner execute
> SEVERE: exception in parsing the paramters
> java.lang.NullPointerException: Cannot invoke "org.eclipse.birt.report.engine.api.IReportEngineFactory.createReportEngine(org.eclipse.birt.report.engine.api.EngineConfig)" because "factory" is null
>         at org.eclipse.birt.report.engine.api.ReportRunner.execute(ReportRunner.java:143)
>         at org.eclipse.birt.report.engine.api.ReportRunner.main(ReportRunner.java:122)

I don't know if that used to work?  My sense is that this hasn't worked in perhaps quite some time.  There are some fundamental class loader problems bootstrapping the OSGi runtime.  In particular the Platform class is loaded by ReportRunner from its URL class loaded, but then later later another instance of Platform.class is loaded by OSGi using a plugin class loaded, so the static Platform.platform is never set on the Platform class seen by the ReportRunner because it's a different copy of the class.  So I think this has nothing to do with the content of these folders but rather a problem in the underlying implementation.

**Comment by wimjongman** [comment]
Doesn't BIRT have its own platform class?

**Comment by merks** [comment]
We could just add it.  Less warnings is better and I don’t think it can hurt.

**Comment by speckyspooky** [comment]
@merks / @wimjongman 

This evening I tested the lates built:

- birt-runtime-4.14.0-202306261418
- birt-runtime-osgi-4.14.0-202306261418

Both only at Windows side (without X-systems) with Tomcat 9 and Java 17, test sequence of both runtimes:

- step 01: WebViewer = successful
- step 02: birt.war = successful
- step 03: command-line = successful

And of course the command lines are working at Windows side:

- example of the "genReport.bat", report is our "hello_world"-report:

>C:/temp/ReportEngine/genReport.bat  -m runrender -f PDF --parameter "paramList=1" -p "paramInteger=1980" -o c:/temp/ReportEngine/results/hello_world-batch.pdf c:/temp/ReportEngine/samples/hello_world.rptdesign


- example of the "java cmd line", report is our "hello_world"-report:

>java -cp "C:/temp/ReportEngine/lib/*" -DBIRT_HOME=C:/temp/ReportEngine/platform org.eclipse.birt.report.engine.api.ReportRunner -m runrender -f PDF -p paramList=1 -p paramInteger=1980 -o c:/temp/ReportEngine/results/hello_world-java.pdf c:/temp/ReportEngine/samples/hello_world.rptdesign


- result screen of the BIRT-runtime-osgi**

![ReportEngine-OSGI](https://github.com/eclipse-birt/birt/assets/41593722/10dabc15-a161-4bab-895c-63e0c5667841)


So currently I see no issues under windows with the latest built.

**Comment by merks** [comment]
I am testing the contents of the target folder in the project where the runtime tests are run so maybe there is some difference.  I will try the real download like what you are doing to confirm it works for me too and then try to figure out the difference.  It would be really great to test this properly with each build.  Anyway, I'm in Montreal now and my time is limited for a few days.  Given it's working from the real zip, there isn't anything to worry about at the moment anyway.  Woo hoo!

**Comment by speckyspooky** [comment]
I think we have all steps done here.
