### ISSUE TITLE
guava class included directly in birt runtime jar

### ISSUE THREAD

**Issue by rajn** [eclipse-birt/birt#1376]
Recently ran into a nosuchmethod and it turns out com.google.common.base.Predicate class is included directly in birt runtime jar. This class is also part of guava-xxx.jar. These two versions of this particular class are different. Wondering why the guava jar is not treated as a dependency for birt runtime? This is creating library conflict issues where opensaml comes into play as it calls guava's Predicate. 
edit: thanks @merks . Added images
birt runtime 
<img width="345" alt="birt_runtime_jar" src="https://github.com/eclipse-birt/birt/assets/3046122/4faa5283-680f-4906-a878-8013c58ee2ff">
guava 
<img width="206" alt="guava_jar" src="https://github.com/eclipse-birt/birt/assets/3046122/9c6849df-8260-4ad2-b6ce-9027bc608252">

**Comment by merks** [comment]
@rajn 

You ought to provide some level of detail.  E.g., where exactly are you seeing this?  It's really easy to copy and paste screen captures...

@speckyspooky 

One thing I found very questionable is the following approach of  copying Maven jars and embedding them as libraries in bundles: 

![image](https://github.com/eclipse-birt/birt/assets/208716/8c7bce8f-703b-4a36-86ac-98a9e67fc5c3)

This _might be_ the probably which which @rajn refers, though I can't be sure.    In think in an OSGi runtime this is maybe not a big deal because the bundle does not export the packages of these libraries, but in a "flattened" non-OSGi runtime this could end up surfacing an **ancient** version of guava.  It's doing some funky thing that I don't understand:

![image](https://github.com/eclipse-birt/birt/assets/208716/e5ab0d2b-0597-4061-98cf-56217e37cbf0)

**Comment by speckyspooky** [comment]
@merks
I take a look into the lib-folder of your screens and the jar files are very very old versions.
The most of them are not longer supported and have better versions.

The way of the usage at libary together with the plugin configuration (extention point) seems to me the try to have the lib-jars accessable at the script context. Because it makes only sence in this way. But this has nothing to do with "real"-PlugIn dependecies.

And perhaps this could be one of our issues to the usage of slf4j.

**Comment by speckyspooky** [comment]
Additional information, we have an old ticke #951 
the reason of it is that there are also the found lib-jars are listed and the hint that the hector-driver of "Apache Cassandra" is "dead" (since 2015).

(At the end it would be an option to exclude Cassandra in full and also such kind of dependencies.)

**Comment by speckyspooky** [comment]
@wimjongman
What is your point of view to the aspect to clean up the cassandra implementation (#951)?
Only the hector-data-source-driver because he is dead and we have different issues with the added jars.

From my point of view it make no sence to "feed a dead horse" and it is a good clearing point.
The steps would be the same like @hvbtup oracle-clean-up (but only cassandra).

**Comment by wimjongman** [comment]
Yes it makes sense to clean it up.

**Comment by speckyspooky** [comment]
The Cassandra Scripted Data Source incl. Hector-runtime is removed with PR https://github.com/eclipse-birt/birt/pull/1419
and will be available with BIRT 4.14

So also the old jars and classes of Hector will removed.
