### ISSUE TITLE
Images with size unit percentage should be sized on the original image size

### ISSUE THREAD

**Issue by speckyspooky** [eclipse-birt/birt#1401]
Based on the discussion #1388 I started a small investigation on the BIRT-behavior.
The result is that the eclipse designer set the height on unit percentage based on the used font size.
The width will be set on percentage unit based on the container arround.

But the original version of the BIRT definition is that the image ratio of an image element if the unit percentage is used should be based on the original image size.

![resize-image](https://github.com/eclipse-birt/birt/assets/41593722/48ada57c-9d17-406a-b3bf-28f520915024)

Therefore I would investigate and try to create a small enhancement to change the behavior on the folowwing elements:
- BIRT-designer
- Preview / HTML emitter
- PDF emitter
- DOCX emitter
- PPTX emitter

The plan is to have the original description (ration based on the original images) supported for raster images.

### The current presentation on the BIRT-designer
=> 1st row percentage unit & 2nd row according px dimensions:

![percentage-designer-error](https://github.com/eclipse-birt/birt/assets/41593722/16f7f298-9761-4c68-9ed5-972826da9730)

### The current presentation on the preview:
=> 1st row percentage unit & 2nd row according px dimensions:

![percentage-preview-error](https://github.com/eclipse-birt/birt/assets/41593722/5cc90283-0eb3-4313-b9f8-5c6cea279e70)

**Comment by hvbtup** [comment]
I think that part of the text excerpt of  that book (I've got one, too) is misleading.

Regarding the text "resizing an image ... typically results in a degradation of its appearance":

I think a better wording would be "may result" instead of "typically results".
This heavily depends on the output format, the type of the image and the environment where the report is read.
For example, in our application, "image" means "photo" in ~ 90% of the cases, "company logo" in 9% of the cases, and "icon" in very rare cases; and the output format is PDF in 98% of the cases.
The photos are stored in a database and it makes no sense to preprocess them to fit to particular pixel dimensions.
So the PDF report contains them with their native dimensions, but with a restricted physical size (preserving aspect ratio).
The reading environment may be a printed report or a PDF file. In the latter case, a viewer may zoom in, so it would be bad practice to store the image with only 72 or 96 dpi at a maximum width/height of eg. 16cm.

However, one reason to resize an image to lower pixel dimensions (before using it in a report) is the crazy pixel dimension that modern cameras and smart phones use (e.g. 30 Megapixels). This only blows up the image files and thus the PDF files.

Regarding "width and height as a percentage of the original size":
Even if EXIF metadata contains DPI settings, in reality a digital photo does not have a concept of "original size".
You could view it on a smartphone display or print a 10m x 6m advertising poster for showing it in an airport or shopping mall.
And AFAIK newer BIRT releases are not (or no longer) able to extract the "physical size" or "DPI" settings from the image metadata. BIRT just assumes 72 or 96 DPI (you know better). And then there's the `imageDPI` setting, and `fitToContainer`.

When we use an image as a company logo, things can be very different. Usually the physical size of the rendered image is (more o less) part of the report specification, and you (as a developer) can prepare a PNG (or SVG) file and choose all those properties in such a way that the result matches the expectations.

A particular difficult case is when you use images for DataMatrix- or QR-Codes or classical Barcodes and the report is to be printed on a label printer. Those printers usually have only 203 DPI or 300 DPI. This means that the size of a little bar or square, when printed, should precisely be a multiple of the the phyiscal dot size; otherwise the printer driver tries to "optimize" the image, resulting in unreadable codes.

Lastly (as a personal remark), I don't like percentage sizes. I always wonder what they mean:
For example, a percentage size in table/grid column isn't related to anything else, it only makes sense if you have several such columns, and their sum does not need to be 100%.
For an image, a percent size could mean "related to the available space" or "related to the 'original size'" (which rarely makes sense in my opinion).

I think we should not try to change the existing behavior, as that would break existing reports.
Instead what we should try to do is precisely document the existing image sizing algorithms behavior and how it differs between the emitters.

**Comment by speckyspooky** [comment]
The "original size" exists for all images because it isn't based on "cm" or "mm" it means based on the pixel size of the images.
So each raster image has an original sized and the DPI define only how many point will be used per inch. At the end it has an impact of the pixel count but nevertheless at the end the width & height is given in "px".

I know that the usage of percentage to define width and height is (I did'nt use it on my self) not the common way.
So I'm completely with you @hvbtup.
But currently it is unusable because if you use percentage the designer display it in another dimension like the preview and also in another way like the PDF.
So I have test cases where the image looks shrinked on the designer, full in HTML and cutted on PDF - the same report and 3 different handlings.

Therefore from my pint of view the change would correct the current behavior to the correct way.
Because it was planned so to do it in this way but cuurently it isn't working.

I can also aks "It is a bug or a feature".

**Comment by hvbtup** [comment]
> The "original size" exists for all images because it isn't based on "cm" or "mm" it means based on the pixel size of the images.

That's what I call "pixel dimensions".

> So each raster image has an original size and the DPI define only how many point will be used per inch.

Yes. I think we both mean the same. We should be careful with the wording.

> ... but nevertheless at the end the width & height is given in "px".

I think that's not true for PDF output. There are no "pixels" in a PDF. Sizes are measured in units with a physical meaning (that's a bit simplified, because there may be scaling factors, but AFAIK doesn't use them).
As you did work with the code recently and know it better than I do, you may be right in a way, nevertheless.
It may be the case that BIRT does its calculations in pixels (or some other fantasy units) and finally uses a DPI value to calculate physical dimensions (measured in PDF units, I guess) from the pixel (or fantasy unit) dimensions.

> Therefore from my point of view the change would correct the current behavior to the correct way.

I think we'll have to carefully balance if we change the behavior or not (except for the appearance in the designer), because probably a lot of existing reports have worked around the existing behavior in ways we don't know.
So this would be a *breaking change* that requires most existing reports to be tested again and in some cases to be modified.

**Comment by speckyspooky** [comment]
Yes, we talk about the same if we would be talk the full correct wording we would use PPI (px) and DPI (dots).
And at the end, yes the emitters transfer the original PPI dimensions into the DPI dimensions for printing.
On the screen level PPI and DPI is the same but on printing level it is not the same and the PPI will be recalcukated to the DPI for the (print) output.
I have seen it on the image size calculcation of the word emitter which is based on the PPI and will be transfered/scaled.

Your last sentence is good point and therefore I like the discussion before I change it.
My view to define the risk is:
- the usage of the percentage unit is very limited by default because in the most cases the stard units will be used
- the designer visualization is wrong
- the emitter vizualization is wrong on the given percentage values (e.g. height calculation isn't correct)
- dependend on the report implementations images will be cutted instead of displaying

All the points can be fixed with the change and the change implemented for "percentage" on element "image".
So we will have no impact on the other more common and standard units.

Yes, this change could have an impact on reports which use percentage units and designed around the issues.
At the end I woudl define the risk as a "minor risk" and we had an improvement like "quality of life".

With the change we are able to explain the behavior without the change we assume why we got what we see.

**Comment by hvbtup** [comment]
> All the points can be fixed with the change and the change implemented for "percentage" on element "image".
So we will have no impact on the other more common and standard units.

If you can assure this, then it's OK for me.

**Comment by speckyspooky** [comment]
Yes absolutly. I will add conditions that the change handling will only be used on images with the unit percentage.

All other units must be unchanged because there a change would be a "nightmare" and all is fine there.
I will also do double checks of the changed areas.

**Comment by speckyspooky** [comment]
@merks 
Hello Ed, the maven-built is currently frozen on the built process of #1406.
It seems to be an issue with the uses Web-Page-URLs and therefore the built stopped directly after the first steps with th error:
```
Error:  Failed to resolve target definition file:/home/runner/work/birt/birt/build/org.eclipse.birt.target/org.eclipse.birt.target.target: Failed to load p2 metadata repository from location https://download.eclipse.org/webtools/repository/latest: Unable to read repository at https://download.eclipse.org/webtools/repository/latest. No repository found at https://download.eclipse.org/webtools/downloads/drops/R3.31.0/R-3.31.0-20230903090456. 
```

I checked the documented path and it seems to me that (I don't know why) old or wrong URLs was used.
Could you please take a look what we can do to fix that built-issue.

Thanks in advance.

![error-p2](https://github.com/eclipse-birt/birt/assets/41593722/ec7afb67-6ee1-4aa1-a303-e2848b0651e8)

**Comment by merks** [comment]
I’ll look first thing in the morning.

**Comment by merks** [comment]
WTP broke their "latest" composite with bad references.  So I fixed the setup and the target platform to avoid that

https://github.com/eclipse-birt/birt/pull/1411

The master build is running now...

**Comment by speckyspooky** [comment]
@merks
Hello Ed, many thanks fo your support and the fixed built.

**Comment by speckyspooky** [comment]
@merks 
Ed some additional question. I merge the master to my fork. The built was started but crashed again
with the message "No space left on device". WHat can I do to solve it, I see this message the firts time:

System.IO.IOException: No space left on device : '/home/runner/runners/2.309.0/_diag/Worker_20230915-181747-utc.log'

![2023-09-15 20_59_16-Update the setup to use the repaired WTP latest release repository (#… · speckys](https://github.com/eclipse-birt/birt/assets/41593722/b35e9d01-dd5c-4052-9fac-1ffead1b6997)

**Comment by merks** [comment]
That’s some GitHub actions infrastructure problem. As long as build on ci.eclipse.org works, all is good.

**Comment by merks** [comment]
If the problem persists you could open a helpdesk issue. They might be able to fix it. 

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues

**Comment by speckyspooky** [comment]
Thanks for your hint. So I will open a ticket there.
