### ISSUE TITLE
BIRT 4.14 null pointer exception with HTML output concerning background image

### ISSUE THREAD

**Issue by reiner-killet** [eclipse-birt/birt#1436]
Hi,
I'm currently testing 4.14 with the RCP designer. All templates were previously running with 4.8. 
WIth the 4.14 HTML emitter I get a null pointer exception:

 java.lang.NullPointerException: Cannot invoke "org.eclipse.birt.report.engine.nLayout.area.style.BackgroundImageInfo.setUri(String)" because "backgroundImage" is null

The same templates are running error-free with DOCX or PDF output.
Can a BIRT developer please view that problem?
I could send rptDesigm & XML files.

Thanks, Reiner

[Full stack trace.txt](https://github.com/eclipse-birt/birt/files/12737868/Full.stack.trace.txt)

**Comment by speckyspooky** [comment]
Hello @reiner-killet,
thanks for your noet and also for the StackTrace. At first yes, there are some changes on the background images.
Based on your StackTrace I figured out the situation that the main object "BackgroundImageInfo" could be null
and therefore the NullPointerException appears.

Could you please provide an example according to your description because all of my reports with backgroundimages on Tabel, Grid, Row, Cell are running.
I tested different options embedded and URL-reference but I'm not able to get your error.

At which element is the background image located?

**Comment by reiner-killet** [comment]
Hello Thomas,

 

We currently do not use any background pictures, only Image tags.

I don’t know where BIRT expects this property.

This what I tried to find out: 

*	Deleted all styles (we use only common styles).
*	Added background pictures to concerned common styles (label, data, text, report, dynamic text).
*	Added background pictures to all tags.

 

I always got the same exception which is not pointing on a certain element.

The element ID would probably be helpful in the message text.

 

Please find enclosed template and sample data.

The workspace path for the pictures should be c:\temp\birt\pisa. 

 

Thanks, Reiner

 

Von: Thomas Gutmann ***@***.***> 
Gesendet: Mittwoch, 27. September 2023 20:22
An: eclipse-birt/birt ***@***.***>
Cc: Reiner Killet ***@***.***>; Mention ***@***.***>
Betreff: Re: [eclipse-birt/birt] BIRT 4.14 null pointer exception with HTML output concerning background image (Issue #1436)

 

Hello @reiner-killet <https://github.com/reiner-killet> ,
thanks for your noet and also for the StackTrace. At first yes, there are some changes on the background images.
Based on your StackTrace I figured out the situation that the main object "BackgroundImageInfo" could be null
and therefore the NullPointerException appears.

Could you please provide an example according to your description because all of my reports with backgroundimages on Tabel, Grid, Row, Cell are running.
I tested different options embedded and URL-reference but I'm not able to get your error.

At which element is the background image located?

**Comment by speckyspooky** [comment]
Nevertheless could you provide me an example report because I didn't get the exception with my test cases.

And additional question do due got the exception only on background images or also at standard images?
You wrote that the error is only with background images.

**Comment by reiner-killet** [comment]
I attached 4 files to my last e-mail. Didn't you receive them?
In https://github.com/eclipse-birt/birt/issues/1436 I'm not able to add files of type xml or rptDesign.

**Comment by merks** [comment]
I think you really need to visit the webpage https://github.com/eclipse-birt/birt/issues/1436 **in a browser** and then drop the attachments into the browser's comment area rather than using an email reply for that purpose.

**Comment by reiner-killet** [comment]
Sorry I did not see, that it accepts zip files:
[Issue-1436-1.zip](https://github.com/eclipse-birt/birt/files/12747362/Issue-1436-1.zip)

**Comment by speckyspooky** [comment]
Many thanks for that and I will take a look into it this evening.

**Comment by speckyspooky** [comment]
@reiner-killet 
This is a very interesting constellation because you use an internal HTML-document definition with an image-tag to create the images. In my point of view this isn't the standard way to handle it but you are right it was running with BIRT 4.8 and 
I have a first drafting version how I can handle this specific situation.
But I have to finalize the draft and to test the standard backrgound functionality with it.

**Comment by speckyspooky** [comment]
The fix is added with PR #1440

The current preview can be created without the Exception and the images will be displayed,
the current result is:

![html-image](https://github.com/eclipse-birt/birt/assets/41593722/84fa86ce-048e-4ab0-a030-df8caa92f455)

**Comment by speckyspooky** [comment]
This issue is fixed with the current nightly built of BIRT 4.14
