### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/rpc/encoding/TypeMappingRegistry when starting WebViewer 

### ISSUE THREAD

**Issue by claesrosell** [eclipse-birt/birt#1451]
There are currently problems with the WebViewer in Master. As seen here: https://github.com/eclipse-birt/birt/issues/1447#issuecomment-1760236651

**Comment by claesrosell** [comment]
We had problems with the javax.xml.rpc-api packages when moving to JavaSE-11 a couple of years ago, which ultimately introduced our own version of that dependency. If I recall correctly it had something to do with the OSGI-headers of the Maven version of javax.xml.rpc .

We recently moved away from our own, modified, version of xml-rpc. We need to investigate if this problem is related to those changes.

**Comment by merks** [comment]
Could someone remind me how to "start the web viewer"?

I see "powered by jetty 10.0.15" in the picture...

**Comment by merks** [comment]
It seems you guys see more than I see.  This is all I see with my partial non-functional migration to jetty 12:

![image](https://github.com/eclipse-birt/birt/assets/208716/64f197e5-8cf2-4095-a987-5050de5148df)

This is with this in my workspace:

https://github.com/eclipse-birt/birt/compare/master...merks:birt:issue-1447

The "missing" class is in my workspace

![image](https://github.com/eclipse-birt/birt/assets/208716/ebd6c69d-5c62-46e2-b8cb-7e70625fa5d1)

And both versions are in the launched IDE:

![image](https://github.com/eclipse-birt/birt/assets/208716/c7b1790b-62fb-4316-8d74-7c79911fee95)

**Comment by speckyspooky** [comment]
Have yu an suggestion how I can support you.
I'm not the expert of the final depencencies but if I can help you please let me know.

I checked the latest changes and I don't know if it has an effect but with PR #1451 the javax.xml.rpc version (seems to be a duplicate was deleted).
I can only see a small difference to the current rpc-version and the deleted version which is the bundle version - deleted version was 1.1.2 and the current orbit version is a 1.1.0.

**Comment by merks** [comment]
Note that the old BIRT version packaged some jars (goodness knows where they came from) into a bundle and that bundle put those jars on the classpath.

It's javax.xml-rpc-api bundle that should be used now, not the very very very old java.xml.rpc bundle.  The rpc-api is at version 1.1.4.  This bundle is provided, as the Plug-in Name suggested, by the Jakarata project and is the most recent version.

I too want to help, but it seems to me as long as we are pulling in a Jetty 10 stack and trying to get that to work on top of the Platform's Jetty 12 dependencies, we are highly unlikely to be successful.  I.e., I still don't understand how this issue is different issue 1447...

**Comment by claesrosell** [comment]
Sorry, I am confused.
Is the current state of master using the 4.30 version of the platform?

**Comment by merks** [comment]
It is confusing.

The target in master is using 4.29:

https://github.com/eclipse-birt/birt/blob/5c22cbe70cc2c78efc654898db61c7f3bd4c1e56/build/org.eclipse.birt.target/org.eclipse.birt.target.target#L344

But that's **just to make the builds work**. 

If you try to install that build into 4.29 2023-09, the IDE doesn't even start.

That is the reason for the prototype PR I created for you.  So on master the setup is like this:

![image](https://github.com/eclipse-birt/birt/assets/208716/926d60a5-24b6-4c25-bdbe-a4c27851f853)

If you double click it opens the properties view  and that needs to be 2023-12 for 4.30 in the target platform.

I think it's futile to try to get 4.29 to work.

If you change it and do Perform Setup Tasks, you'll see it used 4.30 and then will update the target platform to that:

![image](https://github.com/eclipse-birt/birt/assets/208716/7800d75a-0845-4668-8071-343ca8db543b)

In the prototype branch it should be that way already.

**Comment by merks** [comment]
I'll be traveling to EclipseCon so will be slow to answer questions...

**Comment by speckyspooky** [comment]
So currently we have a real mixed dependency situation labeled with 2023-09 (4.29) but used internally 2023-12 (4.30).
If we would have a full rollback to the status before we would be able to create the planned release.

But if I understand it correctly this is not possible and so the are stuck in without anaother option till Jetty 12 may by is changed. Which is hard for the further planning. So I stopped my internal roadmap competely because we don't know when it will be fixed.

**Comment by merks** [comment]
Yes, this is the rock and the hard place problem.  Roll back all the commits is of course possible.  But all the work around such activity is strictly volunteer for me and a rollback approach generates one heck of a lot of work that no one else seems to be able to manage.  My schedules are not completely free to accommodate such things.  E.g., this is EclipseCon week so I really actually have time for thing.  In the end, releases need better planning than "oh, I think we should release now."

It's all a bit of cluster foobar here with the Platform migrating to Jetty 12, but the Jetty project no having all the necessary parts in place.  I could just scream:  😱

**Comment by hvbtup** [comment]
I know this doesn't help others, but I just want to say that it is "only" the Web Viewer which is not working.
The BIRT runtime (when integrated via API and not via the viewer servlet) is working fine for me.

And while I'm not able to help with these build issues, be assured I know how hard you are working and I cross my fingers you will make it work in the end.

**Comment by merks** [comment]
Yes, the fact that the tools all work well is a saving grace.  To a large extent this is the case because there are lots of good tests for that functionality and those tests all run as part of the build.   Whatever isn't tested is easily broken...

If we can get the web viewer functionality to a point where something sort of starts to work or at least fails is some visible way, then I can help, as I did for Equinox a few weeks ago:

https://github.com/eclipse-equinox/equinox/commit/1a51ae9bcab89cf77e600522895e62147956f068

But the state in the following "prototype PR" is such that it quietly just doesn't work at all, so I have no idea where to look:

https://github.com/eclipse-birt/birt/pull/1448

It's been suggested that the missing ee8 bundles are relevant and important, so hopefully that's the case and will be addressed relatively soon.  The work on the ee8 support suggests that a release containing that could be available in about 3 weeks so ideally the Platform will be using such a newer Jetty 12 version.

We all appreciate very much @claesrosell efforts to help on this front!

**Comment by speckyspooky** [comment]
@hvbtup 
From my point of view it is very simplified to say "only" the web viewer.
I don't know in which way you will test from eclipse designer because all emmitters cause currently the 500-error.
So e.g. on eclipse: if I select PDF and get directly 500-Error, if I select XLSX and get 500-Error.
In this case independent whether the viewer is integrated or not we haven't an option to test & develope the reports.
Therefore I would say, it is not "only an Viewer" issue.

Good tho know is the fact that the BIRT-runtime is running!
Next good topic I was able to test some Excel-reports with the new apache POI 5.2.x and the reports was running with your changes @merks .

**Comment by merks** [comment]
At least we have some good news.  It's remains upsetting to be in a state that is not fully functional. 

In any case, I'm also making sure that the Platform does not lock a specific version of Jetty bundles such that we will be in a better position to test and use new Jetty 12 versions that become available:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1444

**Comment by dm-ion** [comment]
Hi, if you are considering updating Axis to the latest Snapshot I have a suggestion. 

AxisServlet.doGet uses a deprecated method (line 265) that has been removed in the latest servlets. 

String url = HttpUtils.getRequestURL(request).toString();

This means that likely the BIRT viewer will not work when run with the Jakarta namespace if you auto-migrate it (eg: using Tomcat's tool) unless you replace this method with something else.

**Comment by claesrosell** [comment]
I just wanted to correct myself. The Orbit version of Axis seems to have the correct Import-Package: headers. For some reason the wrong bundle was picked during debug, even if I am sure that I had excluded it from the launch -config.

**Comment by merks** [comment]
Unfortunately there are quite a few duplicates floating around.  I'm hoping that with m2 done on Friday that there will be better alignment on the newer/latest bundles from Orbit (which I have been testing to ensure they work well with BIRT)...
