### ISSUE TITLE
BIRT 4.15 opening ceremony

### ISSUE THREAD

**Issue by wimjongman** [eclipse-birt/birt#1508]
This issue tracks actions that we must do to start working on BIRT 4.15

**Comment by wimjongman** [comment]
Scan and replace 4.14.0 to 4.15.0 in *.product, *.xml, MANIFEST.MF

**Comment by merks** [comment]
FYI, the target platform is updated, so builds should just continue to work after tomorrow's release.

**Comment by merks** [comment]
@wimjongman @speckyspooky 

I'm wondering about release plans?  I'm not trying to create any pressure, but in general we should try to release around the SimRel release dates:

- https://calendar.google.com/calendar/u/0/embed?src=gchs7nm4nvpm837469ddj9tjlk@group.calendar.google.com&dates=20231201/20240331&hl=en&mode=AGENDA
- https://github.com/eclipse-simrel/.github/blob/main/wiki/Simultaneous_Release.md

I'd like to avoid releasing in the middle of a cycle because that makes it harder for folks building deltas on a branch to locate stable repositories...

**Comment by speckyspooky** [comment]
@merks 
I'm fine with the synchronization around the eclipse SimRel.
So we can use a date around the 13th March for 4.31 (2024-03) and for further updates too.

**Comment by wimjongman** [comment]
Sure. We take whatever is finished in this milestone and move the rest to the next one.

**Comment by wimjongman** [comment]
Great. I created  4.15 Releng #1572 to track the closing of the release.
