### ISSUE TITLE
BIRT 4.14 XLSX column autofit worse than in 4.8

### ISSUE THREAD

**Issue by reiner-killet** [eclipse-birt/birt#1553]
Hi,
in 4.8 there was a helpful autofit of columns in XLSX output.
The respective value had to be characterized as "Preformatted".
The table column hat to be without column width.
Under the above conditions it optimized column width and height. 
In 4.14 the line height is adapted like in 4.8 according to the line breaks in the cells.
But the width is not adequately resized.
The workaround would be: working with static column sizes but actually it a a loss of functionality.
Enclosed please find a report of 4.8:
[Output Price List 4.8.xlsx](https://github.com/eclipse-birt/birt/files/14049252/Output.Price.List.4.8.xlsx)
Here is a report of 4.14:
[Output Price List 4.14.xlsx](https://github.com/eclipse-birt/birt/files/14049258/Output.Price.List.4.14.xlsx)
Here is the data with pictures:
[PsaRptPli.zip](https://github.com/eclipse-birt/birt/files/14049277/PsaRptPli.zip)
And last the template (still in 4.8 mode):
[PSA_RPT_PLI_ENG.zip](https://github.com/eclipse-birt/birt/files/14049308/PSA_RPT_PLI_ENG.zip)
Or is there another method to optimze column width which I did not know?
Thanks, Reiner

**Comment by speckyspooky** [comment]
I have checked your case and yes there is a different behavior.
There is an ExcelEmitter-property to force the auto-fit but it seems to be a changed behavior into the apache poi library for xlsx and therefore the internal calculation is a little bit optimistic for the real column size.
So I will test some details more if there is a good solution of it.

For my it is a little bit strange the behavior at all because normally the auto-fit should be work only with configured Emitter-property also in the old versions. The default setting is deactivated auto-fit. The source-code wasn't changed there. Therefore I mean it is a little bit strange.

The class where I do some testings are "AbstractRealTableHandler.endTable()" and I try to optimize it.

**Comment by speckyspooky** [comment]
Created PR for improve the column auto fit handling PR #1557

**Comment by speckyspooky** [comment]
@reiner-killet
Please be aware I tested lot of cases and there are some at the office library apache poi which is used from BIRT to create XLSX. The library was updated to a newer version with BIRT 4.14 and the library includes self changes of column width colculation. Therefore we won't get the full same results of BIRT 4.8.
Additional on it there is a special XLSX-emitter-property "ExcelEmitter.ForceAutoColWidths" (type: boolean).
If it is true the full autofit handling will be activated but it could be that the reports needs more time for generation.

**Comment by speckyspooky** [comment]
Fix/Improvement is pushed to BIRT master.
