### ISSUE TITLE
Localization not effective in header & footer

### ISSUE THREAD

**Issue by reiner-killet** [eclipse-birt/birt#1556]
Hi,
in 4.14 (4.8, too) in all output formats localization does not work in header & footer.
In the attached sample report the word "INTERNAL PERSON" in the header should be translated in "INTERNE PERSON".
In the footer the word "Page" should be translated in "Seite" and " of " should be translated in " von ".
[PsaRptPrsIntProSal.zip](https://github.com/eclipse-birt/birt/files/14064353/PsaRptPrsIntProSal.zip)
Thanks, Reiner

**Comment by speckyspooky** [comment]
I have tested your report and I cannot confirm your issue.
Because I can create with your report the switch between EN & DE.

I switch the report local on the report in the beforeFactory()-method.
```
importPackage(Packages.java.util);
var lc = new Locale("de_DE");  //  var lc = new Locale("en_US");
reportContext.getDesignHandle().setStringProperty("locale", lc);
```

The only thing what I have changed is that you havn't added the default local file correctly on the source side.

### The configuration and beforeFactory
![2024-01-26 22_22_41-runtime-birt-all-in-one - C__Users_gutma_Downloads_PsaRptPrsIntProSal_PSA_RPT_PR](https://github.com/eclipse-birt/birt/assets/41593722/a5252ab4-87c1-4e29-85e1-ea0c26a043ef)

### Result of your report EN & DE
![2024-01-26 22_23_30-BIRT Report Viewer – Mozilla Firefox](https://github.com/eclipse-birt/birt/assets/41593722/834ba6d5-910d-4f4a-95fb-d7be355a666f)

### Here is your report version little bit changed
[PsaRptPrsIntProSal-locale-example.zip](https://github.com/eclipse-birt/birt/files/14069480/PsaRptPrsIntProSal-locale-example.zip)

**Comment by speckyspooky** [comment]
Please test the changes from your side but I cannot see an problem because it works correctly on header.
Please test the version and the footer version. I will close the issue but we can reopen it later.

If you have further questions we can start a discussion stream.

**Comment by reiner-killet** [comment]
Hi,
the problem I described only appears when there is a mismatch between template name and ressource file name.
=> You can close this ticket. 
In the RCP designer only the ressource file(s) entered for report object have an impact on the translation.
In case of 2 ressource files the upper one wins.
In the runtime the the ressource file(s) entered for report object are completely ignores.
Here, the translation file is programmatically set.
Thanks, Reiner
