### ISSUE TITLE
BIRT Eclipse Installer error

### ISSUE THREAD

**Issue by SteveSchafer-Innovent** [eclipse-birt/birt#1563]
Similar to issue #690.  Attempting to install BIRT dev environment from the link in the README.  Got the following in the Eclipse Updater:

![image](https://github.com/eclipse-birt/birt/assets/8809780/12b37551-1f93-4b05-835a-aa8b48e5cfec)

The important line in the traceback appears to be this:
ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: Batik Transcoder Extension 1.14.0.v20240212-131748 (org.apache.batik.transcoder.birt.ext 1.14.0.v20240212-131748) requires 'osgi.bundle; org.apache.batik.transcoder [1.14.0,1.15.0)' but it could not be found

**Comment by merks** [comment]
Is the git repo pulled to the current state?  It seems to me that project is deleted and that batik 1.17 has been used for quite some time now.

**Comment by SteveSchafer-Innovent** [comment]
It appears to be using my fork.  I didn't expect that because I copied the link from the main BIRT page.  Once I told GitHub to sync my fork that problem went away.  Now I have 185 errors in eclipse but that will be a separate issue if I can't figure it out.

**Comment by merks** [comment]
FYI, I tested this morning:

![image](https://github.com/eclipse-birt/birt/assets/208716/f6dbcf4c-2028-4535-a65d-424e12f840ac)

Note that here I have checkmarked `Show all variables`.  I clone with the original URI, not my fork, and I create the clone in a location relative to the installation so if I create a new installation, I clone a new clone.

The process completes like this:

![image](https://github.com/eclipse-birt/birt/assets/208716/3d74ecd7-fa60-4310-943b-402f9f28f034)

The two maven errors are annoying, but I just delete them.  I'm not sure why or if it's necessary to have maven builders at all.   Certainly there is no need to generate Javadoc in the IDE...

This documentation describes the workflow most folks use when working with  fork:

https://github.com/orgs/eclipse-simrel/discussions/3

With this approach you never need to be concerned with syncing your fork because you never clone the fork and never use the fork's master branch...
