### ISSUE TITLE
BIRT 4.15 milestone, "Build Project" shows 48 JS-library issues due to missing APIs of Rhino 1.7.14 (dependency update #1567)

### ISSUE THREAD

**Issue by speckyspooky** [eclipse-birt/birt#1590]
I started after the finding of the BIRT 4.15 topics a complete project rebuild.
The result was that I got compilation issues with some specific Debugger-JS-Classes:

package: org.eclipse.birt.report.debug.core
- sub-packages: org.eclipse.birt.report.debug.internal.core.vm
- sub-packages: org.eclipse.birt.report.debug.internal.core.vm.js

@merks
Ed, have I forgot something or due you get the same messages if you create a general BIRT project build?
I never used the JS-Debugger and it seems to be not part of our test cases.

### Errors after "Build Project"
![rhino_1 7 14](https://github.com/eclipse-birt/birt/assets/41593722/70d62b4d-c8b1-4123-ac0e-68aab2918866)

**Comment by speckyspooky** [comment]
It seems the the missing debug-classes are part of the rhino engine but I cannot find the classes at the rhino-1.7.14-library.
Can we add this classes as dependencies in another way to avoid the errors?

Package:
org.mozilla.javascript.debug

Source
https://javadoc.io/static/org.mozilla/rhino/1.7.14/org/mozilla/javascript/debug/package-summary.html

**Comment by merks** [comment]
That package is present:

![image](https://github.com/eclipse-birt/birt/assets/208716/8cef4ce4-fd3c-4f98-96b0-533b958631d4)

And the access rules make the internal package accessible:

![image](https://github.com/eclipse-birt/birt/assets/208716/57bcea94-edfb-4828-a2f0-95bffbba9f8d)

So I see no errors and the Maven/Tycho build has no errors.

Maybe you need to do a clean build?

**Comment by merks** [comment]
To see .* resources you must unfilter them:

![image](https://github.com/eclipse-birt/birt/assets/208716/25967ded-a848-4fc9-b045-8a459f7944f2)

To update the target platform you must run the setup tasks for that:

![image](https://github.com/eclipse-birt/birt/assets/208716/bb94cad3-50b9-4699-ba33-f8a86018c42f)

The projects don't need Maven dependencies to be updated.  Don't do that!  There is simply no need to do a Maven build in your workspace,  so avoid that too.  Doing such a build makes a mess of the workspace such that one needs to **do a Project -> Clean...** afterwards to repair the damage.

Of course it's fine to do a Maven build if you need the results for some reason, but it does make a mess of the workspace and you will need to do a clean build afterwards if you want to use the workspace properly again.

The compile error you show was already fixed by my commit.   

https://github.com/eclipse-birt/birt/commit/00fe855a86ae9ae5b2d1ef546b269a685ad5cf5f

Please ensure that you use master (not an outdated master from your fork) but rather the real current master.

**Comment by speckyspooky** [comment]
Thanks for that. I created a completely new branch with all your changes.
I refreshed the "Module Target" and configured the "Filters" according to your hints.

Result:
- I can see the ".classpath" and it looks different from your side - but why (, shall I changed it manually)?
- With the changes of your target it seems to me that we got the issue #1588 & #1589 on top, because know the problem is reproducable on my dev-environment.

![classpath](https://github.com/eclipse-birt/birt/assets/41593722/323039c8-80b3-4b23-91bc-dc157e437b69)

**Comment by merks** [comment]
Yes, using the latest of everything might result in new problems but those are problems that people will see when they install BIRT in tomorrow's release, so need to be fixed.  Please be careful not to mess up the classpaths with maven things.  :-(

**Comment by speckyspooky** [comment]
Please wait with the release, we cannot start with a new version and the 2 bugs.
It would make no sense to do this till we have a stable fix of it.

**Comment by merks** [comment]
Sorry, I mean the SimRel release which is definitely tomorrow.  The BIRT release can happen on our own schedule and of course I will not do that until the lights are green!  😄
