### ISSUE TITLE
BIRT 4.16 opening ceremony

### ISSUE THREAD

**Issue by wimjongman** [eclipse-birt/birt#1611]
- [ ] Update version numbers
- [ ] Update target platform
- [ ] Update Eclipse Project Metadata

**Comment by merks** [comment]
FYI, this is mostly in progress:

https://github.com/eclipse-birt/birt/pull/1609

This time I remembered that I have an Updater.java that did a good job in the past, and I've updated it to cover all the cased, including ones that were overlooked last time.

I should find a good place to keep this, rather than just in my workspace.  But it can a bus hits me before then, here is what I used.

[org.birt.update.zip](https://github.com/eclipse-birt/birt/files/14773310/org.birt.update.zip)

**Comment by speckyspooky** [comment]
I will jump into the front of the bus before you will be catched from him...

Thanks for the version update.

**Comment by merks** [comment]
We've fallen a little behind on creating release records, i.e., no 4.15 and we need a 4.16...

**Comment by wimjongman** [comment]
Done
