### ISSUE TITLE
Preview and auto export of reports is truncating data for Scatter chart of size 11x17 

### ISSUE THREAD

**Issue by pathakravi** [eclipse-birt/birt#1632]
Problem 1: Report with Scatter chart of size 11x17 (Height -11 and width- 17) get truncated data , when **previewed** on browser. Data is truncated from right side. Refer attachment Image 1.

Problem 2: Report with Scatter chart of size 11x17 (Height -11 and width- 17) get truncated data , when exported as format of pdf and Fit to as "auto". Refer attachment 2 and attachment 3.
For the same scenario, Fit to option set as "Actual size" or "Fit to whole page" report exports correctly. 
But when **"Fit to" set as auto exports report with truncated data**. 
Data is truncated from both right and bottom.

Attachment:
Image 1: Report preview with truncated data on right.
![Preview_with_truncate_data_on_right](https://github.com/eclipse-birt/birt/assets/25876427/3ed78cd5-90c8-437e-820f-2a149bd65949)

Image 2: Export as PDF and "Fit to" as auto.
![Export](https://github.com/eclipse-birt/birt/assets/25876427/271c3932-badb-4675-8fce-d1cd1636f3ea)

Image 3: PDF export with truncated data from both right and bottom.
![Pdf_truncate_data_both_right_and_below](https://github.com/eclipse-birt/birt/assets/25876427/2ebdd045-cf09-4d35-87c3-414d410853dd)

**Comment by speckyspooky** [comment]
Could you please add the version of BIRT which was used because the web preview shows differentf from the original birt viewer and is different from the latest version too. Therefore it would be interesting to see which BIRT version you have used.

If you would be able to provide a demo report from your side without external data sources it would be great
because then we could debug based on your example the problem and try to figure out a fix of it.

**Comment by pathakravi** [comment]
BIRT version 4..9

Attachment Image 1: Report viewed in chrome browser.
Attachment Image 2: Report is in pdf format and viewed in chrome browser.

Unit of report size is inch, 11inch x 17inch.

Created and shared demo report for reference. Demo report is attached, "DemoReportTest.zip"
[DemoReportTest.zip](https://github.com/eclipse-birt/birt/files/15022342/DemoReportTest.zip)

**Comment by speckyspooky** [comment]
I tried to execute your report, but sorry for that I would need a runable example.
Your demo version is without parameters and datasets and so I cannot execute the report to test it.
Do you see an option to create a small example for scatter may be based on the classic car model which is integrated part of birt?
Then we woul have a neutral example which is runable on our both sides.

**Comment by speckyspooky** [comment]
I tested a little bit with an own dataset to get your report running.

And then I figured out a question what I not understand.
Because you use as master page the letter format 8.5in x 11.0in but your chart is 11in x 17in.

Why you use a larger size in compare to your printable page...?
The chart should be into the printable area.

**Comment by speckyspooky** [comment]
If we have a runable example report from your side we can try again to analyse your topic.
