### ISSUE TITLE
Data Binding Refresh Button disappeared

### ISSUE THREAD

**Issue by LeonardoIPM** [eclipse-birt/birt#1680]
In the newers versions of BIRT Client, the button "refresh" (when editing a Data Bind, in a table for example), just disappeared.
This button is still in Binding tab (in the right of properties).

I'm comparing Birt 4.4.2 to 4.15. I know it's a huge jump of versions, but this button was usefull for us.

It should be there:
![Refresh Button](https://github.com/eclipse-birt/birt/assets/167772501/fa7cd3f0-0e27-4f30-8169-9fee60897644)

**Comment by speckyspooky** [comment]
Which dialog do you use?

I see that you use a binding dialog, but doesn't figure out the path to it.
The property editor shows the "Refresh"-button on the binding register of a table:

![grafik](https://github.com/eclipse-birt/birt/assets/41593722/15eabd7b-b231-44e0-bb52-02ac217a2f7c)

**Comment by LeonardoIPM** [comment]
![Refresh Button edit databinging](https://github.com/eclipse-birt/birt/assets/167772501/9c89e5ce-d05f-4733-a473-f39e505d667f)

If you access this tab, you won't have a refresh button. In the property editor, it appears normally.

**Comment by speckyspooky** [comment]
Ok, this button is not available since version BIRT 4.6

**Comment by speckyspooky** [comment]
The problem was given 10years ago where the new "Move Up"- & "Move Down"-buttons were introduced cf903c213da3326915125b541b2f3a874d063379.

With the new buttons the Refresh-button is behind the movement buttons.
I aded PR #1681 to solve the problem.

![grafik](https://github.com/eclipse-birt/birt/assets/41593722/2e5baad2-ebd6-4ce4-bb44-4893f15ff4ed)
