### ISSUE TITLE
BIRT 4.15 can't be used under Eclipse RAP

### ISSUE THREAD

**Issue by ManuelMall** [eclipse-birt/birt#1702]
We have an Eclipse RAP application with BIRT embedded. Our current embedded BIRT version is 4.9. When trying to upgrade to BIRT  4.15 we are running into a plug-in dependency issue. 
org.eclise.birt.report.engine
--> Import-Package: org.eclipse.draw2d.geometry
     --> Require-Bundle: org.eclipse.swt
The bundle org.eclipse.swt does not exist in the Eclipse RAP environment therefore it seems we cannot upgrade.

**Comment by merks** [comment]
This was done very recently:

https://github.com/eclipse-birt/birt/commit/3437eb34c9a07419af251965559fe294b7328eee

I see these bundle imports:

![image](https://github.com/eclipse-birt/birt/assets/208716/d0e2dd88-8f23-4749-b067-0a98b2b96129)

Those appear to have been there since 2006.

I suppose those could use package imports (except for the re-export would be problematic).

You could contribute:

https://github.com/eclipse-birt/birt?tab=readme-ov-file#create-a-birt-development-environment

**Comment by ManuelMall** [comment]
Great, so we should just wait for the next BIRT release as the commit fixes the problem. We don't use org.eclipse.birt.ui in our application as we only require the report engine not the designer.

**Comment by merks** [comment]
I would **strongly** suggest testing version 4.16:

https://download.eclipse.org/birt/updates/nightly/latest

Because if there is a problem it can be fixed for the 4.16 release in June, but if you wait until after next release, any subsequent changes will have to wait for the 4.17 release in September.

So I'll assume the problem is addressed and you will reopen if there is some other problem.

**Comment by ManuelMall** [comment]
Thank you, I have confirmed that the dependency issue is resolved for us in the latest BIRT build.
