### ISSUE TITLE
How can i fix this ReportServiceException

### ISSUE THREAD

**Issue by laolj** [eclipse-birt/birt#1719]
There was no problem before, I don't know if it was due to the upgrade of JDK from 8 to 17
org.eclipse.birt.report.service.api.ReportServiceException: ******/tomcat/webapps/birt/documents/BIRTDOCD4AB062E071E23A23619E0C0C348DF60/*******/****.rptdocument doesn't exist or is not a folder.

**Comment by speckyspooky** [comment]
Could you provide please a little bit more information which BIRT version, operating system, wich Tomcat version, etc..

We kno that you use JDK 17 and Tomcat - so if you use BIRT 4.8 then your note is correct because it will need JDK 8.
JDK 11 was supported with BIRT 4.9.
JDK 17 is required since BIRT 4.14.

**Comment by speckyspooky** [comment]
If you cames up with new information we can restart the discussion.
