### ISSUE TITLE
When modifying the power point report do not update the number of pages when we add or remove a slide.

### ISSUE THREAD

**Issue by kavraham** [eclipse-birt/birt#1919]
When I download the report on ppt, on the pages I have the following information:

page 1 of 4, page 2 of 4, page 3 of 4, page 4 of 4.

When I remove an slide I keep only 3 pages I expect to have:
page 1 of 3, page 2 of 3 and page 3 of 3.

But instead of having this results I have:
page 1 of 4, page 2 of 4 and page 3 of 4.

**Comment by speckyspooky** [comment]
Could you please provide some more detail information, which version of BIRT was used?
In best case you can provide us a small example without external dependencies then we would have an option to see your noted behavior..

**Comment by kavraham** [comment]
We are using BIRT 4.17 (latest version).
In the example below you can see that there are only 20 slides, but it is showing "Page x  of 29"
[report - TFM - BIRT (1).pptx.zip](https://github.com/user-attachments/files/17094063/report.-.TFM.-.BIRT.1.pptx.zip)

**Comment by speckyspooky** [comment]
Ok, yes I understand your problem. And it is very easy this answer. The element which is used for the page numbering is a standard PPT-text-element. The number is not the auo-page-counter-element.

So you won't get any changed page numbers. This is a change request because the element cannot changed by default.
There must be done at first the research of the PresentationML (of Office) and afterwards the page number handling for the emitter is to change.

**Comment by speckyspooky** [comment]
So, I have started a small reserach and have new information for you.
At first this topic is not an BIRT issue this topic is based on the PowerPoint-behavior.

I figured out that the standard form at your report "1 of 30 pages" won't be supported by Microsoft-PowerPoint.
[https://support.microsoft.com/en-us/office/show-the-slide-number-and-total-number-of-slides-on-every-slide-e62b363a-a5c4-413e-b7b7-52c1a4d9dd02#:~:text=On%20the%20Insert%20tab%2C%20in,Text%20group%2C%20click%20Slide%20Number](url)

There is no dynamic handling of the total page, so in every case you have to change the total page number manually.

Solution for BIRT and page number. If you use the pageNumber-template then you will get an auto-page-count also at powerpoint side and the number will be changed if you remove slides.

MasterLayout:
![grafik](https://github.com/user-attachments/assets/d1c84f01-69c8-4b0a-baac-b1f68f7cb498)

Example of the created page numbering:
[test_case_slide_page_number.zip](https://github.com/user-attachments/files/17173812/test_case_slide_page_number.zip)

So may be you can change your page-footer-design into this way.
The good thing would be the slides are counted corretcly and only the total page number must be changed.

**Comment by kavraham** [comment]
Thanks, we will check it.

**Comment by kavraham** [comment]
Hi @speckyspooky,
Any update on this?

**Comment by speckyspooky** [comment]
Hi @kavraham,
the page count "3 of 4" is correct. I have written in my post that the number of the currenct page in my case "3" will be set if the autoText was used at the report. But the totalPage "4" cannot be set automatically because you have to change the total page count manually.
You have to set "3 of 3", but with the autoText of BIRT you can avoid that you have to renumber all page numbers.
But for the totalNumber it is a manual step.

And again, this topic is not a BIRT topic, this is how PowerPoint works - therefore I added the link where Microsoft-Support confirm the behavior.
