### ISSUE TITLE
BIRT error reading files with beforeOpen on linux tomcat 9

### ISSUE THREAD

**Issue by alex-axiobit** [eclipse-birt/birt#1926]
When reading database connection details with beforeOpen function on tomcat 9 on linux birt runtime seems to read the values incorrectly. On windows works fine.

Its surrounding the parameters that it reads with the following string: `&quot;` leading to values like  `&quot;mySecretPassword&quot;`

I am reading database connection details with the beforeOpen function and because the connection is unsuccessful it throws multiple errors.
Also, it dumps the entire error in the http response revealing possible sensitive information...

This seem to be a vulnerability.

[error.dump.txt](https://github.com/user-attachments/files/17190339/error.dump.txt)
[env.txt](https://github.com/user-attachments/files/17190352/env.txt)
[beforeOpen.txt](https://github.com/user-attachments/files/17190380/beforeOpen.txt)

**Comment by speckyspooky** [comment]
This is not a BIRT-issue by default because you have extracted all details externally.
So you created an external XML-file with the configuration details.
You have hand written the reading of the config-xml and the XML-parsing.
As last step you set the config-properies and try to start the connection which crash.

But the problem is in my point of view not BIRT by default. The question is which data will arrive the beforeOpen.
Because the error means that and parsed string was the result from the XML-parsing and the content of your note like `&quot;MY_SECRET_USER&quot;` => means `'MY_SECRET_USER'` but the single quote is replaced through xml-entities.

In your special case you should change your configuration handling and remove the single quotes by default.
It could be that your environment create the special XML-string value. But I have never heard and seen that BIRT add a "&quot;" by default to a string.

If you can create a standard DB-connection with your report to your database on linux so all works fine and correct.
In your config case the simplest way is to remove the "quote"-entity and my be you can find the reason of it.

**Comment by alex-axiobit** [comment]
Thanks for the feedback.

I should have mentioned that i have also set the username and password directly from the script just to test if the connection works, and it does this way. I do believe the `&quot;` string is added while parsing the .xml file.
```

    this.setExtensionProperty("odaUser", "MY_SECRET_USER");
    this.setExtensionProperty("odaPassword", "MY_SECRET_PASSWORD");
```

**Comment by speckyspooky** [comment]
You can do a simple test.
You can overwrite the SQL-statement in your beforeOpen to see the parsed XML-values as a result of a simulated SQL.
And may be you will see if there is a problem with the parsed XML-data.

**Comment by speckyspooky** [comment]
I close this issue because it seems to be not an BIRT issue.
Let us know if we cann support you and we can open a discussion of it.
