### ISSUE TITLE
Chart CSS styles classes do not affect charts

### ISSUE THREAD

**Issue by msimanga** [eclipse-birt/birt#1946]
I usually override the default [BIRT built in styles](https://forums.opentext.com/forums/developer/discussion/58256/birt-exturnal-css)  simply by defining them in the stylesheet that I include in the report. The table related styles work well but none of the styles for charts work. The following chart styles don't appear to work:

.chart Chart
.chart-title Chart Title
.chart-value Chart Value Label
.chart-axis Chart Axis Label

Example in my included style.css file I will have 

```css
	.chart-title {
	color: red;
	}
```
This has no effect on the chart. I am using latest BIRT 4.17.0 but I have tested with previous versions in the past and had same issue.

**Comment by speckyspooky** [comment]
Could you please add a small example report without external dependencies then we can test it.
It would be good to have a version from your side to use the same CSS situation from your side.
So it seems that you use external CSS instead of the internal CSS-definition or you have imported your CSS-style...

Therefore an example would be great for testing.

**Comment by msimanga** [comment]
I have attached two files. A report and a CSS file. The CSS file has the BIRT default styles and you will see that the CSS classes for the data table work. The CSS classes for the chart do not have an effect on the chart. As an example .chart-title should make the title in the chart blue but it does not. Same applies to the other chart related CSS classes. 

[chart_css.zip](https://github.com/user-attachments/files/17488450/chart_css.zip)

**Comment by speckyspooky** [comment]
Ok, I tested your report and the topic is that only "chart" is currently supported with BIRT.
The topic in generally is that the charts will be created as SVG and so the style properties can be different from standard html-CSS-properties, e.g. text has no style-property "color" it is "fill".

But the main topic is your reference information are comming from opentext-dev-team and they have there own integrated BIT version which is not the standard BIRT version.

Therfore you can use the style properties only with the opentext-BIRT-version.
If you use the open source version then you can see at the CSS-preference-side which style-classes are supported.

![grafik](https://github.com/user-attachments/assets/f5734869-859c-46c1-9ae5-1a16c362b141)

The alternative for our BIRT is to yous the chart-methods to change the coloring instead of CSS.
Here is a very small example of a color change of the chart-axis-title.

![grafik](https://github.com/user-attachments/assets/ad4d4ad3-51de-43a8-abf2-d8a78cb9c181)

**Comment by msimanga** [comment]
Thank you for the explanation. Makes sense to me. It would be great to be able to apply CSS styles to some chart elements but I will go with your suggested solution. Thank you for your wonderful work in BIRT along with the other developers.
