### ISSUE TITLE
BIRT 4.18 MS: S202411301317 - OSGI version reports throws exception - server error 500

### ISSUE THREAD

**Issue by speckyspooky** [eclipse-birt/birt#1992]
I have started the testing with the release BIRT 4.18 MS: S202411301317 OSGi.

I tested Windows 11 with OpenJDK 17 with Tomcat:
- 9.0.76
- 9.0.93

The app can be started but at the click to execute the report a server error 500 occur.
This error occur with both versions. Retest of BIRT 4.17 is successfully.

### Start screen:
![grafik](https://github.com/user-attachments/assets/2867d8b6-ba89-4e5c-b74f-7b001aa77693)

### Report started:
![grafik](https://github.com/user-attachments/assets/195e834c-1962-4618-a438-c47a84c1f1c9)

**Comment by speckyspooky** [comment]
I have started the testing with the release BIRT 4.18 MS: S202411301317 None-OSGi.

I tested Windows 11 with OpenJDK 17 with Tomcat:

- 9.0.76
- 9.0.93

Application is running and the reports can be done successfully.

**Comment by speckyspooky** [comment]
The only information from the log files are the following information.
But it seems that there is an issue with the "org.apache.commons.logging.LogFactory" which cannot be found.

![grafik](https://github.com/user-attachments/assets/a5d5f953-f46a-41aa-8846-4237da11cff4)

**Comment by merks** [comment]
If you do Ctrl-Shift-T (Open Type) you will see these matches:

![image](https://github.com/user-attachments/assets/f07ebf5b-1d7d-4102-b498-fb4680b08b22)

So there are two sources for that class.

This problem seems similar to problems we've had in the past. 

https://github.com/eclipse-birt/birt/issues/1560

We still don't have tests for it, and no one appears to be manually testing this with any kind of regularity.  I've mentioned in the past, anything that isn't tested will end up being broken.  Moreover, if folks aren't testing such things regularly, the window between when it got broken and when it is noticed will be large and that will make it difficult to track down the cause of the problem...

I recall some instructions somewhere about what is done to manually test this, but where are those instructions?  Perhaps this time around we can record the instructions in a *.md somewhere in the git repository?

**Comment by speckyspooky** [comment]
What I not understand (currently) why is the old jar requested?
I compared th runtime-bversion & runtim-OSGi-version and both bundles have at the plugin-folder the  "commons-logging_1.3.4.jar".
This is working for the standard-runtime but not for the OSGi-version or may be some other jar import the correct LogFactory for the standard-runtime.

![grafik](https://github.com/user-attachments/assets/33817402-e8da-48ac-b5db-bcc7543b6d92)

**Comment by merks** [comment]
What about the org.apache.commons.logging_1.2.0 jar?   I know there are things in Orbit that specifically require this older jar...

I'd do some more comparing myself but with this being release day, there are 100 things to do...

---

Only 5 nightly builds are retained so that generally doesn't go back very far...

**Comment by speckyspooky** [comment]
I have tested the oldest version of the nightly builds (N202411271252) and this has already the same problem.

**Comment by merks** [comment]
Could you please write instructions for how someone else can test what you are testing? We should have those in a *.md file somewhere in the git repository this time so I can find them in the future.

**Comment by speckyspooky** [comment]
I can do it. The simple thing is, I clicked on our 2 test links on our starting page to generate the test reports:

![grafik](https://github.com/user-attachments/assets/e5838b67-991d-4663-83f0-8fd6a44381fb)

**Comment by merks** [comment]
Note the timing of all this is rather poor relative to my personal availability.  Today I have been swamped with rolling out the old release and starting up the new release.  The next two days are personal time off so I will be of no help for those days.  I will not have time for the next days.

There is this difference between 4.17 and 4.18:

![image](https://github.com/user-attachments/assets/e013b1dd-f141-4691-b230-a44e72c8d471)

But both bundles provide the "missing" class.

---

I know there was some process for copying/unzipping something into some folder in tomcat installation and starting tomcat.  Assume there is some person who is clueless about all the steps involved.

**Comment by speckyspooky** [comment]
The added jar of "org.apache.commons.commons-logging" was added with #1822.
But this was BIRT 4.17...

**Comment by speckyspooky** [comment]
The logging factory is switched from "org.apache.commons.logging" to "org.apache.commons.commons-logging" and must be copied from platform/plugins-folder to the WEB-INF/lib-folder.

The PR #1994 includes the change of the OSGi-build.

(The old logging.jar is not longer available at the  platform/plugins-folder.)

**Comment by merks** [comment]
@speckyspooky 

This build contains your fix:

https://download.eclipse.org/birt/updates/nightly/N202412041727

**Comment by speckyspooky** [comment]
The new build is tested sucessfully. The BIRT 4.8 OSGi version is running and the demo-reports can be created.

**Comment by merks** [comment]
Woo hoo. 🥳
