### ISSUE TITLE
Fix Warnings

### ISSUE THREAD

**Issue by wimjongman** [eclipse-birt/birt#706]
We have 130K warnings which are not good for the performance and image of the project.

Either:

* Suppress the warnings in the project preferences
* Fix them

**Comment by SteveSchafer-Innovent** [comment]
I'll work on these as I have time.  If someone else wants to help we should agree on some kind of division of areas so we don't collide.

**Comment by hvbtup** [comment]
Regarding NLS-warnings: I had started with adding NON-NLS comments on individual lines in the Word and Excel emitters, but that is rather tedious work, wouldn't recommend that. I think it's better to switch those warning off for whole classes. Most of the Java classes in the engine do not contain translatable strings.

**Comment by SteveSchafer-Innovent** [comment]
Eclipse will automatically add the NON-NLS comments everywhere in quick-fix.  That removes the tedious aspect.  Would this then be a better solution?

**Comment by wimjongman** [comment]
No because it will also non-nls the text that has to be translated.

Switching off the error in the preferences would be the only quickfix

**Comment by hvbtup** [comment]
I still think that after skim reading a *.java source file (scanning for translatable messages) in most cases SuppressWarnings can be added to whole classes.

As a non-english developer and user I think that only texts *inside the IDE* should be translated, whereas all those text that only occur *at runtime* (debug, warning, info, error messages) should strictly *not* be translated.

The reasoning behind this is: If you are not a developer, then those texts are all gibberish for your anyway. 

I know this from ~30 years.  experience. Only in a handful of cases has any of our users understood the root cause of a stack trace.

Those messages are understandable only for developers. And even then, you often have to search the internet for more information. Since we don't have unique message ids (such like ORA-01403 for Oracle databases with the meaning "No data found" or "Keine Daten gefunden" in German), it would be counter-productive to have a e.g. a German translation. Developers are expected to understand a basic subset of English anyway, and when searching the internet, the chances to find some useful information are much higher with an english search phrase.

**Comment by wimjongman** [comment]
I do not agree with the first paragraph. The rest I do agree with.

**Comment by SteveSchafer-Innovent** [comment]
@wimjongman if you don't agree with suppressing warnings on whole classes then you wouldn't agree to changing the severity level to "ignore" across the board.  Are we left with examining individual string constants?

**Comment by wimjongman** [comment]
If there is no plan to externalize translatable strings then I'm fine with changing the severity level. If the plan does come up in the future it is easy to bump the severity level back to a warning.

**Comment by SteveSchafer-Innovent** [comment]
I submitted a PR to change the severity level given that we can change it back in the future if necessary.

**Comment by SteveSchafer-Innovent** [comment]
@wimjongman did you close this intentionally?  I only fixed a small fraction of the warnings.

**Comment by wimjongman** [comment]
Steve, it was closed automatically because of the linked PR that was merged. Thanks for reopening.

**Comment by claesrosell** [comment]
I think that it would be great to fix 7316 warnings with "Clean Up"! It would take a long time to fix those manually.

**Comment by wimjongman** [comment]
Sure. Let's go! I'm in favor of an aggressive, but sensible source clean-up. With sensible I mean that there are some cleanup options that are questionable.

**Comment by SteveSchafer-Innovent** [comment]
Okay I'll start with the clean-up actions I listed to fix the 7316 warnings.  After that we can look at additional clean-ups but I think it should be a separate issue.

**Comment by wimjongman** [comment]
The problem with multiple cleanup commits is the pollution it gives in the history.

**Comment by SteveSchafer-Innovent** [comment]
Well then we can do one massive clean-up, but which clean-up's do you think are questionable?

**Comment by wimjongman** [comment]
Steve, I have attached a very aggressive cleanup. Maybe we can go over it and remove anything we 
don't like. You can import it via the preferences

[birtcleanup.xml](https://github.com/eclipse/birt/files/8110785/birtcleanup.xml.txt)

**Comment by SteveSchafer-Innovent** [comment]
I personally like "Remove redundant comparison statements" and "Remove unreachable block" in the Unnecessary Code section.  The latter might fix a warning.
I think many of the items in the Performance section are worth doing.
I like "Pull up assignment" in Code Style because I think it improves readability.
I personally am a fan of using 'final' modifiers wherever possible because it can catch more errors.

Everything else I agree with or don't care about.

**Comment by wimjongman** [comment]
> I personally like "Remove redundant comparison statements" and "Remove unreachable block" in the Unnecessary Code section. The latter might fix a warning.
> I think many of the items in the Performance section are worth doing.
> I like "Pull up assignment" in Code Style because I think it improves readability.

These ones are fine with me

> I personally am a fan of using 'final' modifiers wherever possible because it can catch more errors.

It is better but not used much. I can do without this one.

**Comment by SteveSchafer-Innovent** [comment]
I'm getting an unexpected refactoring error. 
`Root exception:
java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.LambdaExpression.setBody(LambdaExpression.java:284)
	at org.eclipse.jdt.internal.corext.fix.LambdaExpressionsFixCore$CreateLambdaOperation.rewriteAST(LambdaExpressionsFixCore.java:654)
	at org.eclipse.jdt.internal.corext.fix.CompilationUnitRewriteOperationsFixCore.createChange(CompilationUnitRewriteOperationsFixCore.java:98)
	at org.eclipse.jdt.internal.ui.fix.CleanUpFixWrapper.createChange(CleanUpFixWrapper.java:39)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.calculateChange(CleanUpRefactoring.java:775)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring$CleanUpASTRequestor.calculateSolutions(CleanUpRefactoring.java:301)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring$CleanUpASTRequestor.acceptAST(CleanUpRefactoring.java:279)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:930)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:614)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:954)
	at org.eclipse.jdt.internal.corext.dom.ASTBatchParser.createASTs(ASTBatchParser.java:82)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring$CleanUpFixpointIterator.next(CleanUpRefactoring.java:399)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.cleanUpProject(CleanUpRefactoring.java:682)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.checkFinalConditions(CleanUpRefactoring.java:642)
	at org.eclipse.ltk.core.refactoring.CheckConditionsOperation.run(CheckConditionsOperation.java:86)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:122)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:210)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2338)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
`
This was caused by "Convert functional interface instances" in "Java Feature"
After deselecting that clean-up it succeeded but now there are 43 errors in the code

It seems some of these clean-ups are less then perfect.  For example, it converted
`fontAttribs.put(TextAttribute.SIZE, new Float(fd.getSize() * getDpiResolution() / 72d));`
to
`fontAttribs.put(TextAttribute.SIZE, Float.valueOf((float) fd.getSize() * getDpiResolution() / 72d));`
but since it didn't add parentheses, the cast didn't work and the value passed to valueOf was a double.

In another instance it converted an inner class to static but didn't change the instantiation so it was still being instantiated as an instance of an object.

I'm going to have to disable clean-ups until I can eliminate all the errors.

**Comment by wimjongman** [comment]
Oops, that is not very reassuring for the code that it did convert. I have filed https://bugs.eclipse.org/bugs/show_bug.cgi?id=578880

**Comment by SteveSchafer-Innovent** [comment]
I'll determine which clean-ups cause which errors and post the info to your bug.

**Comment by SteveSchafer-Innovent** [comment]
I've been able to eliminate the clean-up actions that were causing errors and will submit a PR.

**Comment by SteveSchafer-Innovent** [comment]
Looks like the commit by Claes "Replace iText with OpenPDF #767 (#814) caused 612 errors in eclipse, mostly because it can't find com.lowagie and other PDF related errors.  Any suggestions how I can remove these errors?

**Comment by claesrosell** [comment]
@SteveSchafer-Innovent, try to reload your target platform.

**Comment by claesrosell** [comment]
On the theme "less then perfect clean-ups", this is the reason why #836 currently fails :
The "Replace String concatenation by StringBuilder" clean up converts

```
	public String getDisplayLabel(Module module, int level) {
		String displayLabel = super.getDisplayLabel(module, level);
		if (level == IDesignElementModel.FULL_LABEL) {
			String name = getStringProperty(module, IReportItemModel.DATA_SET_PROP);
			name = limitStringLength(name);
			if (!StringUtil.isBlank(name)) {
				displayLabel += "(" + name + ")"; //$NON-NLS-1$//$NON-NLS-2$
			}
		}
		return displayLabel;
	}
```

to

```
	@Override
	public String getDisplayLabel(Module module, int level) {
		StringBuilder displayLabel = new StringBuilder().append(super.getDisplayLabel(module, level));
		if (level == IDesignElementModel.FULL_LABEL) {
			String name = getStringProperty(module, IReportItemModel.DATA_SET_PROP);
			name = limitStringLength(name);
			if (!StringUtil.isBlank(name)) {
				displayLabel.append("(").append(name).append(")"); //$NON-NLS-1$//$NON-NLS-2$
			}
		}
		return displayLabel.toString();
	}
```

The old implementation will return null if super.getDisplayLabel() returns null and level != IDesignElementModel.FULL_LABEL , and the new implementation will return "null" under the same circumstances.

This is of cause suspicious code to begin with since the original code will throw a NPE if super.getDisplayLabel() returns null and level == IDesignElementModel.FULL_LABEL. but it is not a good sign that the clean up changes the behavior of the method.

I was initially very optimistic about these "automatic clean-ups" but I am starting to get scared instead.

**Comment by SteveSchafer-Innovent** [comment]
Not done yet.

**Comment by SteveSchafer-Innovent** [comment]
Are there reasons not to move all Bundle-RequiredExecutionEnvironment's to JavaSE-11?

**Comment by wimjongman** [comment]
I can't think of a reason.

**Comment by wimjongman** [comment]
I looked at it but there seem to be no bundles left to move:

![image](https://user-images.githubusercontent.com/180969/156882005-866e6695-3c21-4aa0-89d1-3df025f74f72.png)

**Comment by SteveSchafer-Innovent** [comment]
I would like to run BIRT all-in-one to see how some changes affect the UI but when I try to launch it from eclipse debug or run I get this error:

!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

This used to work back in November.  Something changed.  Any idea how I can make it work?

**Comment by wimjongman** [comment]
Steve, the run config was updated with https://github.com/eclipse/birt/pull/853

**Comment by wimjongman** [comment]
Is this still active or can this be closed?

**Comment by wimjongman** [comment]
Closing. Please open a new issue if you want to work more on this,
