### ISSUE TITLE
Sign our builds

### ISSUE THREAD

**Issue by wimjongman** [eclipse-birt/birt#871]
We have signed most parts of our builds but still we did not do 

* Mac notarization 
* Sign a couple of source bundles
* and also some dependencies are not signed

See issue  _Sign our builds #817_ for more background

![image](https://user-images.githubusercontent.com/180969/158770065-c27f8619-6b82-4110-93d6-34c55d708eb2.png)

**Comment by wimjongman** [comment]
@merks is this resolved with the new builds?

**Comment by merks** [comment]
The build does to signing and gets everything from Orbit which is either jar-signed or PGP signed.  Let me run a report and I'll post the link in a few minutes.

**Comment by merks** [comment]
Unfortunately there is still one ancient artifact that is unsigned:

- https://download.eclipse.org/oomph/archive/reports-extra/birt/updates/milestone/latest/download.eclipse.org/birt/updates/milestone/latest/https___download.eclipse.org_birt_updates_milestone_S202311210608.html
- https://download.eclipse.org/oomph/archive/reports-extra/birt/updates/milestone/latest/download.eclipse.org/birt/updates/milestone/latest/https___download.eclipse.org_birt_updates_milestone_S202311210608/jakarta.servlet_5.0.0.v20210105-0527.html

Let me see if I can determine what is dragging this in...

**Comment by merks** [comment]
That's not so ancient...

**Comment by merks** [comment]
@nitind

It's pulled in by WTP:

![image](https://github.com/eclipse-birt/birt/assets/208716/f9927d4f-c14b-4c20-a826-455f31ef367f)

Orbit has this newer version but because it has no qualifier, OSGi considers it an older version:

![image](https://github.com/eclipse-birt/birt/assets/208716/68f07a11-8931-46fd-975b-b74828a5fe27)

That makes it hard to get rid of the older one with the weak signature unless one ensures the target platform can't see the older one with the qualifier or one specifies the version exactly in the target platform.

This same bundle in SimRel has a PGP signature:

https://download.eclipse.org/releases/2023-12/202311171000/buildInfo/archive/download.eclipse.org/releases/2023-12/202311171000/index/jakarta.servlet_5.0.0.v20210105-0527.html

That's because I finally gave up on getting everyone to sign things or to use new things and PGP sign everything that is not otherwise signed...

**Comment by merks** [comment]
What I might be able to do is build BIRT against the release train repository in the target platform such that the build picks up PGP signed version.

**Comment by wimjongman** [comment]
Ok. I'm glad with what we got already.

**Comment by wimjongman** [comment]
Closing for 4.14.
