### ISSUE TITLE
Remove Mylyn and PDE from BIRT product

### ISSUE THREAD

**Issue by wimjongman** [eclipse-birt/birt#899]
These two products have not much to do with report designers.

**Comment by hvbtup** [comment]
+1 for removing Mylyn, not 100% sure about PDE.

Developing a plugin (even if it is for BIRT) is so very different from developing reports, that > 99% of the BIRT users will never do this. OTOH if one really needs to develop a plugin for BIRT (I once did and I've started to develop a QR-code plugin in my free time) than the all-in-one developer environment is the natural choice.

**Comment by wimjongman** [comment]
Wouldn't you say that the SDK is the natural choice in that case?

https://github.com/eclipse/birt#create-a-birt-development-environment

**Comment by hvbtup** [comment]
I can only speak for myself here.

When I developed the first plugin ~ 10 years ago, there was a tutorial and it was not too complicated to create a plugin with the All-in-one-designer. I would have been totally helpless with the SDK then.

When I started with the QR-code plugin, last weekend, I *did* use the SDK - but only because I already have the SDK installed and I didn't want to run *3* Eclipse environments (1=SDK run --> 2=all-in-one for plugin development  debug --> 3=all-in-one to test the plugin). Still, the SDK ist too much for my little brain - I didn't know where to start, so I cloned the sample RotatedText plugin as a workaround.

IMHO it was much easier with the All-in-one environment, where basically you could just choose between creating a report/library/template or a plugin. OTOH it is helpful to have the full source code at hand for debugging the plugin.

**Comment by wimjongman** [comment]
Yes, it makes sense. We will keep PDE in then. IIRC PDE was required in the early days because of the error log being there. I have ported that view to Eclipse Platform a couple of years ago.
