### ISSUE TITLE
Calender picker for Date report parameter

### ISSUE THREAD

**Issue by krishnakittu** [eclipse-birt/birt#926]
HI Team,
As of now we have workaround to display calendar picker in report parameter. Can You include as a part of product itself

**Comment by claesrosell** [comment]
What kind of workaround are you using? Does it include patches that you could contribute to the project?

**Comment by krishnakittu** [comment]
I am using [this](https://balendra15.wordpress.com/2011/05/05/how-to-show-date-picker-for-date-field-in-parameter-page/) as a workaround.

**Comment by hvbtup** [comment]
I'm not familiar with HTML front-end development, but is an additional Javascript library actually necessary?
Wouldn't a simple <input type="date"> show a date picker automatically in current browsers?

	<html>
	<body>
	<form>
	Datum: <input type="date">
	</form>
	</body>
	</html>

At least this works for me in Chrome and Firefox.

**Comment by krishnakittu** [comment]
Yeah excellent. We can use this(Html5 entity). Almost all the browsers support this except IE. You can check [here](https://caniuse.com/?search=date)
Can we add this change to the repo?

**Comment by claesrosell** [comment]
I have finally looked into this "code situation".
I really like the idea to add more control types for parameters in Birt, the UI control situation in html is far better now, compared to when Birt was first released.
But, I want to do this properly, by first adding support for the new controls in the Birt designer and then create corresponding controls in the web viewer.
Unfortunately, the "control type handing" in Birt is in some parts hard-coded, and adding new control types will be a lot of work.
If we do this I guess that it is a good idea to add support for more control types at the same time, since we will need to increase the version number on the design files.

Any suggestions of other new control types, available in html now a days?

**Comment by hvbtup** [comment]
In the hundreds of reports I developed over the years, the parameters were always (in descending order of magnitude) strings, dates, booleans and integers (in fact never a decimal value), and in very rare cases a time (without date).

One use case which I could imagine could be useful for others is to have a file name as a parameter. But I'm uncertain if supporting a file chooser dialog would be a good idea at all - wouldn't it try to _upload_ the file _content_ somewhere? Does the report need the file location as a string or its content as a blob? Do we have to think about security here? Certainly not something we should introduce thoughtless.

From my point of view, anything else (for example, using a color as a report parameter) is of no practical use..

But I never used the parameter form actually except from the designer to supply one unique "report job id", and the application is a database application, so I might be biased.

**Comment by speckyspooky** [comment]
This topic is solved with the latest built (final version BIRT 4.14) based on enhancement of #1356.
